# Generated by Django 3.0 on 2020-11-14 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vnumber', models.CharField(max_length=100)),
                ('vname', models.CharField(max_length=200)),
                ('vseat', models.IntegerField()),
                ('vroute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.VehicleRoute')),
                ('vtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.VehicleType')),
            ],
        ),
    ]
