# Generated by Django 3.0 on 2020-11-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleroute',
            name='route',
        ),
        migrations.AddField(
            model_name='vehicleroute',
            name='routefrom',
            field=models.CharField(default='Dharan', max_length=200),
        ),
        migrations.AddField(
            model_name='vehicleroute',
            name='routeto',
            field=models.CharField(default='KTM', max_length=200),
        ),
    ]
