# Generated by Django 3.0 on 2020-11-14 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20201114_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRouteTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routeto', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='VehicleRoute',
            new_name='VehicleRouteFrom',
        ),
        migrations.RenameField(
            model_name='vehicleroutefrom',
            old_name='route',
            new_name='routefrom',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vroute',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vroutefrom',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tickets.VehicleRouteFrom'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vrouteto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tickets.VehicleRouteTo'),
        ),
    ]
