# Generated by Django 3.0 on 2020-11-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20201114_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vdescription',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vimage',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
