# Generated by Django 3.0 on 2020-11-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20201114_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vimage',
            field=models.ImageField(blank=True, default='images/1.jpg', upload_to='images/'),
        ),
    ]
