# Generated by Django 3.1.3 on 2020-11-15 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20201114_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vimage',
            field=models.ImageField(blank=True, default='images/1.jpg', upload_to='images/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='AvailableTickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vtickets', models.CharField(max_length=100)),
                ('vnumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.vehicle')),
            ],
        ),
    ]
