# Generated by Django 3.1.3 on 2020-11-15 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20201115_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletickets',
            name='vtickets',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('A7', 'A7'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4'), ('B5', 'B5'), ('B6', 'B6'), ('B7', 'B7')], max_length=100),
        ),
        migrations.CreateModel(
            name='TicketDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vdeparttime', models.DateTimeField(verbose_name='related date time')),
                ('vticketprice', models.FloatField()),
                ('vtickets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.availabletickets')),
            ],
        ),
    ]
